"use client";

import React, { useState } from "react";
import { trpc } from "~/trpc/client";
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "~/components/ui/card";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Badge } from "~/components/ui/badge";
import { Spinner } from "~/components/ui/spinner";
import { Brain, Search, Calendar, ArrowRight, Layers } from "lucide-react";
import Link from "next/link";
import { formatDate as formatUtilityDate } from "~/lib/utils";

export default function PRDsPage() {
  const [search, setSearch] = useState("");

  const { data: envelope, isLoading } = trpc.prd.list.useQuery();
  const prdList = envelope?.data ?? [];

  const filteredPrds = prdList.filter((item) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const titleMatch = (item.content as any)?.title?.toLowerCase().includes(search.toLowerCase());
    const reqTitleMatch = item.featureRequest?.title?.toLowerCase().includes(search.toLowerCase());
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const descMatch = (item.content as any)?.executiveSummary?.toLowerCase().includes(search.toLowerCase());
    return titleMatch || reqTitleMatch || descMatch;
  });

  const formatDate = (dateStr: string) => formatUtilityDate(dateStr, {
    month: "short",
    day: "numeric",
    year: "numeric"
  });

  if (isLoading) {
    return (
      <div className="flex justify-center items-center py-24">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight bg-gradient-to-r from-foreground to-muted-foreground bg-clip-text text-transparent flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            Product Requirements Documents
          </h1>
          <p className="text-sm text-muted-foreground">
            Review and manage structured technical specifications generated by ShipFlow AI.
          </p>
        </div>
      </div>

      {/* Search Toolbar */}
      <div className="flex flex-col md:flex-row items-center gap-4 bg-card/20 p-4 border border-border/40 rounded-xl backdrop-blur-sm">
        <div className="relative w-full md:w-96">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search PRD title, feature request, summary..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9 bg-background/50 border-border/60"
          />
        </div>
      </div>

      {/* Grid List */}
      {filteredPrds.length === 0 ? (
        <div className="text-center py-20 border border-dashed border-border/60 rounded-xl bg-card/10 flex flex-col items-center justify-center space-y-4">
          <div className="p-4 rounded-full bg-primary/10 text-primary">
            <Brain className="h-10 w-10 animate-pulse" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-semibold">No PRDs Found</h3>
            <p className="text-sm text-muted-foreground max-w-sm mx-auto">
              {search
                ? "No generated documents match your search term. Try adjusting your query."
                : "Product Requirements Documents are created automatically from Ready for PRD feature requests."}
            </p>
          </div>
          {!search && (
            <Button asChild>
              <Link href="/feature-requests">Browse Feature Requests</Link>
            </Button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredPrds.map((item) => {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const content = item.content as any;
            const prdTitle = content?.title || `PRD for ${item.featureRequest.title}`;
            const summary = content?.executiveSummary || "No summary provided.";

            return (
              <Card key={item.id} className="border border-border/40 bg-card/40 hover:bg-accent/5 hover:border-primary/20 transition-all flex flex-col justify-between group h-full">
                <CardHeader className="space-y-2.5">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-primary flex items-center gap-1">
                      <Layers className="h-3 w-3" />
                      Version {item.version}
                    </span>
                    <Badge variant="secondary" className="text-[9px] font-bold uppercase tracking-wider">
                      v{item.version}
                    </Badge>
                  </div>
                  <CardTitle className="text-base font-bold line-clamp-1 group-hover:text-primary transition-colors">
                    {prdTitle}
                  </CardTitle>
                  <CardDescription className="text-xs text-muted-foreground/80 line-clamp-2 min-h-[2rem]">
                    {summary}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4 pt-0">
                  <div className="border-t border-border/20 pt-4 flex flex-col gap-2">
                    <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                      <span className="font-medium">Origin Request:</span>
                      <span className="truncate max-w-[200px] font-semibold text-foreground">
                        {item.featureRequest.title}
                      </span>
                    </div>
                    <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                      <span className="font-medium">Generated At:</span>
                      <span className="flex items-center gap-1 font-semibold text-foreground">
                        <Calendar className="h-3 w-3" />
                        {formatDate(item.createdAt)}
                      </span>
                    </div>
                  </div>
                  <div className="flex justify-end pt-2 border-t border-border/10">
                    <Button size="sm" variant="ghost" asChild className="group-hover:text-primary transition-colors pr-2">
                      <Link href={`/prds/${item.id}`} className="gap-1 text-xs">
                        <span>Open Document</span>
                        <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" />
                      </Link>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
